Implemented performConnection - to be tested
noluyorAbi/C-Project pull request #10
Opened 2024-11-22 17:10 UTC by jpeter96

performConnection implemented and to be tested

2024-11-24 23:10 UTC, cininja reviewed
Damit unser Projekt einigermaßen einheitlich ist: kannst du return 0 oder -1, zu **EXIT_SUCCESS und EXIT_FAILURE** ausbessern und statt perror, **fprintf und stderr** verwenden. Abgesehen davon, kann ich deinen Code nicht testen, weil mir als Error angezeigt wird, dass performConnection.h nicht gefunden werden kann. Ich schätze das liegt daran, dass die Programme in unterschiedlichen Ordnern liegen. Wenn möglich teste bitte selber zuerst und mach dann nochmal mit ausgebesserter Version den PR.

2024-11-25 12:15 UTC, mvritz commented on modules/tcp_performConnection/performConnection.c
> +    return -1;
```suggestion
    return EXIT_FAILURE;
```

2024-11-25 12:20 UTC, mvritz requested changes

2024-11-25 12:20 UTC, mvritz commented on modules/tcp_performConnection/performConnection.c
> +    return -1;
```suggestion
    return EXIT_FAILURE;
```

2024-11-25 12:20 UTC, mvritz commented on modules/tcp_performConnection/performConnection.c
> +  return 0;
```suggestion
  return EXIT_SUCCESS;
```

2024-11-25 16:09 UTC, jpeter96 commented on modules/tcp_performConnection/performConnection.c
> +  // 1. Receive greeting from server
alright

2024-11-25 21:29 UTC, closed without merging