Feat: Add shared memory functionality and tests
noluyorAbi/C-Project pull request #21
Opened 2024-12-05 19:52 UTC by noluyorAbi

# Pull Request: Implementierung des Shared-Memory-Bereichs

## Beschreibung

Dieser Pull Request fügt dem Projekt einen **Shared-Memory-Bereich** hinzu, der die Kommunikation zwischen den Prozessen **Gameserver**, **Thinker** und **Connector** optimiert. Die Implementierung unterstützt eine dynamische Anzahl von Spielern und gewährleistet eine effiziente Speicherverwaltung.

## Änderungen

1. **Shared-Memory-Module hinzugefügt:**
   - **Dateien:**
     - `modules/shared_memory/shared_memory.c`
     - `modules/shared_memory/shared_memory.h`
   - **Strukturen:**
     ```c
     typedef struct {
       char gameName[256];     // Spielname vom Gameserver
       int playerNumber;       // Eigene Spielernummer
       int playerCount;        // Anzahl der Spieler
       pid_t thinkerPID;       // PID des Thinker-Prozesses
       pid_t connectorPID;     // PID des Connector-Prozesses
       Player players[];       // Dynamisches Array der Spieler
     } SharedMemory;

     typedef struct {
       int playerNumber;       // Spielernummer
       char playerName[128];   // Name des Spielers
       bool isRegistered;      // Registrierungsstatus
     } Player;
     ```
   - **Funktionen:**
     - `createSharedMemory(int numPlayers)`: Reserviert ein Shared-Memory-Segment.
     - `attachSharedMemory(int shmid)`: Bindet das Segment an den Adressraum.
     - `detachSharedMemory(SharedMemory *shm)`: Trennt das Segment.
     - `removeSharedMemory(int shmid)`: Entfernt das Segment.

2. **Integration in das Hauptprojekt:**
   - **`main.c`:**
     - Einbindung von `shared_memory.c`.
     - Nutzung der Shared-Memory-Datenstruktur zur Verwaltung der Spielparameter.
   - **`args_parser.c` & `args_parser.h`:**
     - Verbesserte Argumentenparsing-Logik zur Unterstützung dynamischer Spielerzahlen.

3. **Tests hinzugefügt:**
   - **Dateien:**
     - `tests/test_sharedMemory/test_sharedMemory.c`
     - `tests/test_sharedMemory/README.md`
   - **Testfälle:**
     - Initialisierung und Anbindung von Shared-Memory für verschiedene Spielerzahlen.
     - Datenmanipulation und Validierung der Spielerinformationen.
     - Fehlerbehandlung bei ungültigen Shared-Memory-IDs und -Zeigern.
     - Sicherstellung der korrekten Trennung und Entfernung der Shared-Memory-Segmente.

4. **CI-Pipeline angepasst (`.github/workflows/ci.yml`):**
   - **Workflow-Name geändert:**
     - Von `C Project Build, Memory Leak Check, and Deployment Pipeline` zu `C Project Build, Memory Leak Check, and Shared Memory Test`.
   - **Neue Schritte hinzugefügt:**
     - Kompilierung und Ausführung der Shared-Memory-Tests.
     - Valgrind-Analyse zur Überprüfung auf Speicherlecks.
   - **Deployment-Schritt entfernt:** Fokus auf Build und Test.

5. **Projektstruktur und Dokumentation aktualisiert:**
   - **`.gitignore`:**
     - Hinzufügen des `/bin`-Verzeichnisses:
       ```
       # Bin directory
       /bin
       ```
   - **`README.md`:**
     - Aktualisierung der Verzeichnisstruktur.
     - Beschreibung der neuen Shared-Memory-Module und der zugehörigen Tests.

## Begründung

- **Effiziente Kommunikation:** Shared Memory ermöglicht eine schnelle und ressourcenschonende Kommunikation zwischen Prozessen, ideal für Multiplayer-Anwendungen.
- **Skalierbarkeit:** Die flexible Datenstruktur unterstützt zukünftige Erweiterungen und verschiedene Spieltypen mit unterschiedlicher Spieleranzahl.
- **Ressourcenmanagement:** Sicherstellung der ordnungsgemäßen Freigabe von Shared-Memory-Segmenten verhindert Speicherlecks.
- **Automatisierte Qualitätssicherung:** Integration der Tests in die CI-Pipeline gewährleistet die Stabilität und Fehlerfreiheit der neuen Funktionalitäten.

## Zusammenfassung

Mit dieser Implementierung wird die Speicherverwaltung des Projekts optimiert und die Grundlage für eine skalierbare Multiplayer-Architektur geschaffen. Die umfassenden Tests und Anpassungen in der CI-Pipeline sichern die Zuverlässigkeit und Qualität der neuen Shared-Memory-Funktionalität.

2024-12-06 11:56 UTC, jpeter96 submitted a review, later dismissed

2024-12-18 20:57 UTC, mvritz requested changes

2024-12-18 20:57 UTC, mvritz commented on modules/shared_memory/shared_memory.c
> +    fprintf(stderr, "shmdt failed: %s\n", strerror(errno));
```suggestion
fprintf(stderr, "[ERROR] Failed to create shared memory: %s\n", strerror(errno));
```

2024-12-18 20:57 UTC, mvritz commented on modules/shared_memory/shared_memory.c
> +int detachSharedMemory(SharedMemory *shm) {
docs?

2024-12-18 20:57 UTC, mvritz commented on modules/shared_memory/shared_memory.c
> +int detachSharedMemory(SharedMemory *shm) {
I would add something like this tbh as an utility function:

size_t calculateShmSize(int numPlayers) {
    return sizeof(SharedMemory) + numPlayers * sizeof(Player);
}

2024-12-18 21:25 UTC, noluyorAbi commented
# Detaillierte Änderungen am Shared Memory Modul

## Übersicht

In diesem Commit wurden umfassende Verbesserungen und Erweiterungen am Shared Memory Modul vorgenommen. Die Änderungen umfassen:

- **Verbesserte Fehlerbehandlung** in den Shared Memory Funktionen.
- **Erweiterung der Funktionalität** zur Initialisierung und Bereinigung des Shared Memory Segments.
- **Refaktorierung der Header-Datei** zur besseren Strukturierung und Dokumentation.
- **Erstellung und Aktualisierung der Testfälle** zur Sicherstellung der Funktionalität und Robustheit.
- **Entfernung veralteter Testdateien**.

Im Folgenden werden die Änderungen im Detail erläutert.

## Änderungen in `shared_memory.c`

### 1. Header-Includes

- **Änderung des Include-Pfads:**
  ```diff
  -#include "shared_memory.h"
  +#include "./shared_memory.h"
  ```
  Der Include-Pfad wurde explizit auf das aktuelle Verzeichnis gesetzt, um mögliche Konflikte mit anderen Header-Dateien zu vermeiden.

- **Zusätzliche Includes:**
  ```diff
  +#include <unistd.h>
  ```
  Die Bibliothek `<unistd.h>` wurde hinzugefügt, um Funktionen wie `getpid()` nutzen zu können.

### 2. Definitionen und Konstanten

- **Definition der maximalen Spielerzahl:**
  ```c
  #define MAX_PLAYERS 100 // Definieren Sie eine maximale Anzahl von Spielern
  ```
  Eine Konstante zur Begrenzung der Anzahl der Spieler wurde hinzugefügt, um Überläufe und unerwartetes Verhalten zu verhindern. **Hinweis:** `MAX_PLAYERS` ist derzeit auf 100 gesetzt, um umfangreiche Testfälle zu ermöglichen. In der Produktionsumgebung wird die Anzahl der Spieler jedoch durch den `args_parser` auf 1 oder 2 begrenzt, sodass `MAX_PLAYERS` für Testspezifische Zwecke auf 100 belassen werden kann.

### 3. Verbesserte Fehlerbehandlung

- **Validierung der Eingabeparameter:**
  ```c
  if (numPlayers < 0 || numPlayers > MAX_PLAYERS) {
    fprintf(stderr, "Ungültige Anzahl von Spielern: %d. Muss zwischen 0 und %d liegen.\n", numPlayers, MAX_PLAYERS);
    return SHM_ERROR_CREATION;
  }
  ```
  Eingaben werden nun validiert, um sicherzustellen, dass die Anzahl der Spieler innerhalb der erlaubten Grenzen liegt. Zusätzlich übernimmt der `args_parser` bereits die Überprüfung, ob die Anzahl der Spieler auf 1 oder 2 beschränkt ist, wodurch in der Regel `numPlayers` nicht über diese Werte hinausgehen sollte.

- **Verwendung von `perror` für Fehlermeldungen:**
  ```diff
  -fprintf(stderr, "shmget failed: %s\n", strerror(errno));
  +perror("shmget fehlgeschlagen");
  ```
  `perror` wird verwendet, um detaillierte Fehlermeldungen basierend auf `errno` auszugeben.

### 4. Rückgabewerte und Fehlercodes

- **Einführung von spezifischen Fehlercodes:**
  ```c
  typedef enum {
    SHM_SUCCESS = 0,
    SHM_ERROR_CREATION = -1,
    SHM_ERROR_ATTACH = -2,
    SHM_ERROR_DETACH = -3,
    SHM_ERROR_REMOVE = -4,
  } ShmError;
  ```
  Die Funktionen geben nun spezifische Fehlercodes zurück, anstatt nur `-1`, um eine genauere Fehlerdiagnose zu ermöglichen.

### 5. Erweiterte Funktionalitäten

- **Initialisierung des Shared Memory Segments:**
  ```c
  int initSharedMemory(int numPlayers, const char *gameName, int playerNumber,
                       pid_t thinkerPID, pid_t connectorPID) {
    // Validierungen und Initialisierungen
  }
  ```
  Eine neue Funktion zur Initialisierung des Shared Memory Segments wurde hinzugefügt, die zusätzliche Parameter wie `gameName`, `playerNumber`, `thinkerPID` und `connectorPID` akzeptiert.

- **Bereinigung des Shared Memory Segments:**
  ```c
  void cleanupSharedMemory(int shmid, SharedMemory *shm) {
    // Detach und Remove mit Fehlerüberprüfung
  }
  ```
  Eine Funktion zur sauberen Freigabe des Shared Memory Segments wurde hinzugefügt.

## Änderungen in `shared_memory.h`

### 1. Strukturverbesserungen

- **Erweiterung der `SharedMemory` Struktur:**
  ```c
  typedef struct {
    char gameName[256];
    int playerNumber;
    int playerCount;
    pid_t thinkerPID;
    pid_t connectorPID;
    Player players[];
  } SharedMemory;
  ```
  Zusätzliche Felder wie `gameName`, `thinkerPID` und `connectorPID` wurden hinzugefügt, um mehr Kontextinformationen im Shared Memory zu speichern.

### 2. Fehlercodes und Dokumentation

- **Einführung von Fehlercodes:**
  ```c
  typedef enum {
    SHM_SUCCESS = 0,
    SHM_ERROR_CREATION = -1,
    SHM_ERROR_ATTACH = -2,
    SHM_ERROR_DETACH = -3,
    SHM_ERROR_REMOVE = -4,
  } ShmError;
  ```
  Spezifische Fehlercodes wurden definiert, um die Fehlerbehandlung zu verbessern.

- **Detaillierte Funktionsdokumentation:**
  Jede Funktion wurde mit ausführlichen Kommentaren versehen, die den Zweck, die Parameter und die Rückgabewerte erläutern. Beispiel:
  ```c
  /**
   * @brief Erstellt ein Shared-Memory-Segment.
   *
   * @param numPlayers Die Anzahl der Spieler, für die Platz reserviert werden soll.
   * @return int Die ID des erstellten Shared-Memory-Segments oder ein Fehlercode (siehe ShmError).
   */
  int createSharedMemory(int numPlayers);
  ```

## Änderungen in den Testdateien (`test_sharedMemory.c`)

### 1. Refaktorierung der Tests

- **Direktes Einbinden des Headers:**
  ```diff
  -#include "../../modules/shared_memory/shared_memory.c"
  +#include "../../modules/shared_memory/shared_memory.h" // Include shared_memory.h directly
  ```
  Die Implementierungsdatei wird nicht mehr direkt eingebunden, stattdessen wird der Header genutzt, um die Funktionen zu testen.

- **Einführung von Testzählern:**
  ```c
  int PASS_COUNT = 0;
  int FAIL_COUNT = 0;
  ```
  Zähler zur Nachverfolgung der bestandenen und fehlgeschlagenen Tests wurden hinzugefügt.

### 2. Erweiterte Testfunktionen

- **Hilfsfunktion zur Berichterstattung:**
  ```c
  void report_test(const char *test_name, bool passed, const char *message) {
    if (passed) {
      printf("[PASS] %s: %s\n", test_name, message);
      PASS_COUNT++;
    } else {
      printf("[FAIL] %s: %s\n", test_name, message);
      FAIL_COUNT++;
    }
  }
  ```
  Eine Funktion zur einheitlichen Darstellung der Testergebnisse wurde eingeführt.

- **Neue Testfälle:**
  - **`testSharedMemoryCreateAndAttach`**: Testet das Erstellen und Anhängen eines Shared Memory Segments.
  - **`testInitSharedMemory`**: Überprüft die Initialisierung des Shared Memory Segments mit verschiedenen Parametern.
  - **`testInvalidInput`**: Testet das Verhalten der Funktionen bei ungültigen Eingaben.
  - **`testErrorHandling`**: Überprüft die Fehlerbehandlung bei ungültigen Operationen.
  - **`testBoundaryConditions`**: Testet die Funktionen an den Grenzwerten der erlaubten Eingaben (z.B. 0 und 100 Spieler).

- **Entfernung veralteter Testdateien:**
  ```diff
  deleted file mode 100755
  index 136c12f..0000000
  Binary files a/tests/test_sharedMemory/test_sharedMemory and /dev/null differ
  ```
  Alte ausführbare Testdateien wurden entfernt, um Platz für die neuen, verbesserten Testskripte zu schaffen.

### 3. Verbesserte Testausgabe

- **Detaillierte Informationsausgaben:**
  ```c
  printf("[INFO] Shared memory created with shmid: %d\n", shmid);
  ```
  Zusätzliche Informationen während der Tests erleichtern das Debugging und die Nachverfolgung des Testverlaufs.

- **Zusammenfassung der Testergebnisse:**
  ```c
  printf("[SUMMARY] Bestanden: %d, Fehlgeschlagen: %d\n", PASS_COUNT, FAIL_COUNT);
  return (FAIL_COUNT == 0) ? 0 : 1;
  ```
  Am Ende der Testausführung wird eine Zusammenfassung der bestandenen und fehlgeschlagenen Tests angezeigt.

## Gründe für die Änderungen

1. **Verbesserte Robustheit:** Durch die Einführung spezifischer Fehlercodes und erweiterter Fehlerbehandlungen wird das Modul robuster und weniger anfällig für unerwartete Eingaben oder Zustände.

2. **Erhöhte Funktionalität:** Die neuen Funktionen zur Initialisierung und Bereinigung des Shared Memory Segments bieten eine bessere Kontrolle und Flexibilität bei der Nutzung des Moduls.

3. **Bessere Testabdeckung:** Die erweiterten und neuen Testfälle stellen sicher, dass das Modul in verschiedenen Szenarien korrekt funktioniert, einschließlich Grenzwert- u [...]

2024-12-18 22:49 UTC, noluyorAbi commented
/review

2024-12-19 19:09 UTC, noluyorAbi commented
/review

2024-12-19 19:13 UTC, merged