Perform connection
noluyorAbi/C-Project pull request #23
Opened 2024-12-06 13:55 UTC by jpeter96

Implemented: "Testing The Client" (on MS01 code-base) pl review 
Still to be done: Test performConnection with LRZ-Server

2024-12-06 23:23 UTC, noluyorAbi commented
Preparing review...

2024-12-06 23:26 UTC, noluyorAbi commented
Preparing review...

2024-12-06 23:27 UTC, noluyorAbi commented
Preparing review...

2024-12-06 23:27 UTC, noluyorAbi commented
## PR Reviewer Guide 🔍

<table>
<tr><td>⏱️&nbsp;<strong>Estimated effort to review</strong>: 3 🔵🔵🔵⚪⚪</td></tr>
<tr><td>🧪&nbsp;<strong>PR contains tests</strong></td></tr>
<tr><td>🔒&nbsp;<strong>No security concerns identified</strong></td></tr>
<tr><td>⚡&nbsp;<strong>Key issues to review</strong><br><br>

<a href='https://github.com/noluyorAbi/C-Project/pull/23/files#diff-984e74d1b03c4aafe88a26e4b34a74cf255bbc04741004fc1751bf82cc522357R72-R73'><strong>Consistency Issue</strong></a><br>The return values for error handling in `performConnection` function have been changed from `EXIT_FAILURE` to `-1`. It is recommended to use standard exit codes for consistency and clarity.

<a href='https://github.com/noluyorAbi/C-Project/pull/23/files#diff-984e74d1b03c4aafe88a26e4b34a74cf255bbc04741004fc1751bf82cc522357R109-R110'><strong>Consistency Issue</strong></a><br>The return values for error handling in `performConnection` function have been changed from `EXIT_FAILURE` to `-1`. It is recommended to use standard exit codes for consistency and clarity.

<a href='https://github.com/noluyorAbi/C-Project/pull/23/files#diff-984e74d1b03c4aafe88a26e4b34a74cf255bbc04741004fc1751bf82cc522357R145-R146'><strong>Consistency Issue</strong></a><br>The return values for error handling in `performConnection` function have been changed from `EXIT_FAILURE` to `-1`. It is recommended to use standard exit codes for consistency and clarity.

</td></tr>
</table>

2024-12-10 18:57 UTC, noluyorAbi commented on modules/tcp_performConnection/performConnection.c
> +    return -1;
```suggestion
    return EXIT_FAILURE;
```
We use EXIT_FAILURE & EXIT_SUCCESS as  standard

2024-12-10 18:57 UTC, noluyorAbi commented on modules/tcp_performConnection/performConnection.c
> +    return -1;
here too

2024-12-10 18:58 UTC, noluyorAbi commented on modules/tcp_performConnection/performConnection.c
> +    if (receiveMessage(sockfd, buffer, BUFFER_SIZE) != 0) {
see above

2024-12-10 19:33 UTC, noluyorAbi commented
I implemented some comments and adjustments, but I couldn’t get `test_create_tcp_connection.c` to work even after several attempts. Did it work for you?

Maybe we should add Makefiles to the folders to ensure the tests run correctly, even for the tutors reviewing our code.

2024-12-10 19:37 UTC, noluyorAbi requested changes

2024-12-10 19:37 UTC, noluyorAbi commented on tests/test_args_parser/test_args_parser.c
> +// Hilfsfunktion, um Kommandozeilenargumente zu simulieren
Readmes can stay in german

2024-12-19 22:23 UTC, cininja commented
This pull request will be closed, as numerous changes and tests are already implemented on a different branch, making most of the adjustments in this request likely redundant.

2024-12-19 22:23 UTC, closed without merging